#!/bin/bash
set -x
OSDP_PATH=/opt/osdp-conformance
CMDPATH=${OSDP_PATH}/tmp/open_osdp_command.json
CMDPATHX=${OSDP_PATH}/run/CP/open_osdp_command.json

OUI_INID=007532
CMD_CPRXSIZE=18
DETAILS_CPRXSIZE=0002

echo  >${CMDPATH} "{"
echo >>${CMDPATH} "  \"command\" : \"mfg\","
echo >>${CMDPATH} "  \"oui\" : \"${OUI_INID}\","
echo >>${CMDPATH} "  \"command-id\" : \"${CMD_CPRXSIZE}\","
echo >>${CMDPATH} "  \"command-specific-data\" : \"${DETAILS_CPRXSIZE}\""
echo >>${CMDPATH} "}"
sudo -n cp ${CMDPATH} ${CMDPATHX}
sudo -n ${OSDP_PATH}/bin/HUP-CP

