#!/bin/bash
set -x
OSDP_HOME=/opt/osdp-conformance
echo executing test 2-2-2
bash /$OSDP_HOME}/bin/do-CP-command conform_2_2_2
echo sleep to resync at new speed
sleep 5
echo executing test 2-2-3
bash /$OSDP_HOME}/bin/do-CP-command conform_2_2_3
echo sleep to resync at new speed
sleep 5
echo executing test 2-2-4
bash /$OSDP_HOME}/bin/do-CP-command conform_2_2_4
echo sleep to resync at new speed
sleep 5
echo executing test 2-2-1
bash /$OSDP_HOME}/bin/do-CP-command conform_2_2_1
echo sleep to resync at new speed
sleep 5

