#!/bin/bash
set -x
rm -vf /opt/osdp-conformance/log/report.log
echo start CP
echo sleep to stabilize
sleep 5
echo executing test 2-6-1
bash /opt/osdp-conformance/bin/do-CP-command conform_2_6_1
echo executing test 3-2-1
bash /opt/osdp-conformance/bin/do-CP-command identify
echo executing test 3-3-1
bash /opt/osdp-conformance/bin/do-CP-command capabilities
echo executing test 3-5-1
/opt/osdp-conformance/bin/do-CP-command local_status
echo executing test 3-6-1
/opt/osdp-conformance/bin/do-CP-command input_status
echo executing test 3-7-1
/opt/osdp-conformance/bin/do-CP-command output_status
echo executing test 3-8-1
/opt/osdp-conformance/bin/do-CP-command reader_status
echo executing test 3-9-1
/opt/osdp-conformance/bin/do-CP-command conform_3_9_1
echo executing test 3-12-1
CMDPATH=/opt/osdp-conformance/run/CP/open_osdp_command.json
echo  >${CMDPATH} "{"
echo >>${CMDPATH} "   \"command\" : \"text\""
echo >>${CMDPATH} "  ,\"message\" : \"TEST_3-12-1\""
echo >>${CMDPATH} "}"
/opt/osdp-conformance/bin/HUP-CP
sleep 2
echo request test 4-5-2
echo request test 4-5-2
/opt/osdp-conformance/bin/do-CP-command output_status
echo request test 4-5-2
/opt/osdp-conformance/request-exercise-PD 4-5-2
echo request test 4-5-3
/opt/osdp-conformance/request-exercise-PD 4-5-3
echo requesting test 4-6-1
/opt/osdp-conformance/request-exercise-PD 4-6-1
echo executing test 4-7-1
/opt/osdp-conformance/bin/do-CP-command outstat
echo request test 4-7-2
/opt/osdp-conformance/request-exercise-PD 4-7-2
echo request test 4-8-1
/opt/osdp-conformance/request-exercise-PD 4-8-1
echo  >${CMDPATH} "{"
echo >>${CMDPATH} "   \"command\" : \"text\""
echo >>${CMDPATH} "  ,\"message\" : \"Conformance_Test_Complete\""
echo >>${CMDPATH} "}"
/opt/osdp-conformance/bin/HUP-CP
sleep 2

echo generate test report
bash /opt/osdp-conformance/bin/do-CP-command dump_status
cp /opt/osdp-conformance/log/report.log osdp-conformance-report_`date +%F_%H_%M`.txt
ls -l 


