#!/bin/bash

# (C)Copyright 2015-2024 Smithee Solutions LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#   http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


TEXT=123456789ABCDEF0123456789ABCDEF0
OSDP_PATH=/opt/osdp-conformance
CMDPATH=${OSDP_PATH}/tmp/open_osdp_command.json
CMDPATHX=${OSDP_PATH}/run/CP/open_osdp_command.json
sudo -n echo  >${CMDPATH} "{"
sudo -n echo >>${CMDPATH} "   \"command\" : \"text\"",
sudo -n echo >>${CMDPATH} "  \"message\" : \"${TEXT}\"",
sudo -n echo >>${CMDPATH} "  \"#\" : \"created by 79-text from UI\""
sudo -n echo >>${CMDPATH} "}"
sudo -n cp ${CMDPATH} ${CMDPATHX}

sudo -n ${OSDP_PATH}/bin/HUP-CP

