#!/bin/bash
RESPONSES=/opt/osdp-conformance/responses
LOG=/opt/osdp-conformance/log
mkdir -p ${LOG}
# arg 5 is the json blob
echo >${RESPONSES}/response_RAW $5
echo >>${LOG}/actions.log osdp_RAW called $1 $2 $3 $4 $5 $6 $7 $8


