#!/bin/bash
mkdir -p /opt/osdp-conformance/log
echo >>/opt/osdp-conformance/log/actions.log osdp_PDID called $1 $2 $3 $4 $5 $6 $7 $8
echo >/opt/osdp-conformance/tmp/response_PDID \
  $1 $2 $3 $4 $5 $6 $7 $8

