#!/bin/bash
set -x
#/opt/open-osdp/bin/write-osdp-CP-command identify
#/opt/open-osdp/bin/HUP-CP

# 80800180 as 26 bit is P=1 FC=0x01 CH=0x01 P=1

#                        rrffbbbb--data--
#                                .0.1.2.3
CMD_CYPRESS_WIEGAND_OUT="00001A0080800180"
# example per doc 128 bits 56/72 filler

#                        rrffbbbb--data--
#                                .0.1.2.3.4.5.6(and 72 filler bits)
#CMD_CYPRESS_WIEGAND_OUT="0000800000000000000001000000000000000000"

"command" : "mfg",
"oui" : "CA446C",
"command-id" : "9",
"command-specific-data" : "11223344",
"#" : "_end"

