#!/bin/bash
OSDP_PATH=/opt/osdp-conformance
echo ACTION: calling send-challenge
echo ACTION: argument is $1
${OSDP_PATH}/run/CP/test/send-challenge \
  >>/opt/osdp-conformance/log/action.log \
  2>>/opt/osdp-conformance/log/stderr &

