#!/bin/bash

usermod --shell /bin/bash www-data

echo make sure www-data has sudo and bash

mkdir -p /opt/osdp-conformance/run/ACU
mkdir -p /opt/osdp-conformance/run/MON
mkdir -p /opt/osdp-conformance/run/PD

# set up default parameter files 

echo "NOTICE: OSDP parameters may be updated."

cp /opt/osdp-conformance/run/ACU/open-osdp-params-ACU.json /opt/osdp-conformance/run/ACU/open-osdp-params.json
cp /opt/osdp-conformance/run/PD/open-osdp-params-PD.json /opt/osdp-conformance/run/PD/open-osdp-params.json
cp /opt/osdp-conformance/run/MON/open-osdp-params-MON.json /opt/osdp-conformance/run/MON/open-osdp-params.json

# resave settings
cd /tmp
/opt/tester/cgi-bin/save-osdp-conformance >stdout 2>stderr

echo >>/opt/osdp-conformance/log/install.log libosdp-conformance was installed.

