#!/bin/bash
set -x
OSDP_PATH=/opt/osdp-conformance
CMDPATH=${OSDP_PATH}/tmp/open_osdp_command.json
CMDPATHX=${OSDP_PATH}/run/CP/open_osdp_command.json
mkdir -p ${OSDP_PATH}/run/CP
echo  >${CMDPATH} "{"
echo >>${CMDPATH} "  \"command\" : \"buzz\","
echo >>${CMDPATH} "  \"#\" : \"created by 69-buzz in test\""
echo >>${CMDPATH} "}"
sudo -n cp ${CMDPATH} ${CMDPATHX}
sudo -n ${OSDP_PATH}/bin/HUP-CP

