#!/bin/bash

# (C)Copyright 2017-2018 Smithee Solutions LLC
# (C)Copyright 2015-2017 Smithee,Spelvin,Agnew & Plinge, Inc.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#   http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo "Content-type: text/html"
echo ""

echo "<HTML><HEAD><TITLE>COMSET</TITLE>"
echo "<META HTTP-EQUIV=\"REFRESH\" CONTENT=\"1;URL=/Test-PD.html\"><HEAD>"
echo "<BODY>"
echo "<BR>"
echo "<PRE>"
date
ROLE=`cat /opt/osdp-conformance/etc/current_role`
OSDP_PATH=/opt/osdp-conformance
CMDPATH=${OSDP_PATH}/tmp/open_osdp_command.json
CMDPATHX=${OSDP_PATH}/run/${ROLE}/open_osdp_command.json

# unilaterally clear out the last temp command
sudo -n rm -f ${CMDPATH}

sudo -n echo  >${CMDPATH} "{"
sudo -n echo >>${CMDPATH} "   \"command\" : \"keypad\"",
sudo -n echo >>${CMDPATH} "  \"digits\" : \"1234\"",
sudo -n echo >>${CMDPATH} "  \"#\" : \"created by do-keypad from UI\""
sudo -n echo >>${CMDPATH} "}"
sudo -n cp ${CMDPATH} ${CMDPATHX}

sudo -n ${OSDP_PATH}/bin/HUP-${ROLE}
echo "</PRE></BODY></HTML>"

