#!/bin/bash

# (C)Copyright 2017-2018 Smithee Solutions LLC
# (C)Copyright 2015-2017 Smithee,Spelvin,Agnew & Plinge, Inc.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#   http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo "Content-type: text/html"
echo ""

echo "<HTML><HEAD><TITLE>COMSET</TITLE>"
URL=/osdp-conformance-CP.html
echo "<META HTTP-EQUIV=\"REFRESH\""
echo "CONTENT=\"1;URL=${URL}\">"
echo "<HEAD>"
echo "<BODY>"
echo "<BR>"
echo "<PRE>"
date
OSDP_PATH=/opt/osdp-conformance
CMDPATH=${OSDP_PATH}/tmp/open_osdp_command.json
CMDPATHX=${OSDP_PATH}/run/CP/open_osdp_command.json
sudo -n echo  >${CMDPATH} "{"
sudo -n echo >>${CMDPATH} "   \"command\" : \"verbosity\"",
sudo -n echo >>${CMDPATH} "  \"level\" : \"$1\"",
sudo -n echo >>${CMDPATH} "  \"#\" : \"created by do-verbosity from UI\""
sudo -n echo >>${CMDPATH} "}"
sudo -n cp ${CMDPATH} ${CMDPATHX}

sudo -n ${OSDP_PATH}/bin/HUP-CP

echo "Set verbosity to level $1"

echo "</PRE></BODY></HTML>"

