#!/bin/bash
# (C)2022 Smithee Solutions LLC
CMDPATH=/opt/osdp-conformance/tmp/transfer-command.json
echo  >${CMDPATH} "{\"command\":\"$1\", \"file-type\":\"$2\", \"file\":\"$3\"}"
sudo -n /opt/osdp-conformance/bin/open-osdp-kick ACU <${CMDPATH}

