#!/bin/bash
set -x
OSDP_PATH=/opt/osdp-conformance
CMDPATH=${OSDP_PATH}/tmp/open_osdp_command.json
CMDPATHX=${OSDP_PATH}/run/CP/open_osdp_command.json

OUI_INID=007532
CMD_KP_ACT=19
DETAILS_KP_ACT_TIME=8813

echo  >${CMDPATH} "{"
echo >>${CMDPATH} "  \"command\" : \"mfg\","
echo >>${CMDPATH} "  \"oui\" : \"${OUI_INID}\","
echo >>${CMDPATH} "  \"command-id\" : \"${CMD_KP_ACT}\","
echo >>${CMDPATH} "  \"command-specific-data\" : \"${DETAILS_KP_ACT_TIME}\""
echo >>${CMDPATH} "}"
sudo -n cp ${CMDPATH} ${CMDPATHX}
sudo -n ${OSDP_PATH}/bin/HUP-CP

